# Schema for the configuration files of the cache_api_example module.
cache_api_example.settings:
  type: config_object
  label: 'cache_api_example settings'
  mapping:
    example:
      type: string
      label: 'Example'
